// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TESTE3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TESTE3', async function() {
    await driver.get("https://ultima.school/")
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    await driver.findElement(By.linkText("Log In")).click()
    await driver.findElement(By.id("user_pass")).sendKeys("***")
    await driver.findElement(By.id("loginform")).click()
    assert(await driver.findElement(By.linkText("Forgot Password?")).getText() == "Forgot Password?")
    await driver.close()
  })
})
